### ISSUE TITLE
Electron v8 deprecation warning

### ISSUE THREAD

**Issue by stuartambient** [brrd/electron-tabs#103] opened 2020-04-05 22:12 UTC
**Describe the bug**
This is not so much a bug but for versions 8 and above of Electron.  I am using v8 and I get:

> DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9

**To Reproduce**
Use v8 and above of Electron.

**Expected behavior**
I'm assuming that electron-tabs sends the webview event to main in the background.   I can see the event using 'will-attach-webview' in main.  I was trying to add src from there but still the same warning.  

**Please complete the following information**
 - OS: Windows 10
 - electron-tabs version:  0.12.1
 - Electron version: 8

** Additionally **
Is there a reason that only 'file' protocol maybe used as opposed to a custom scheme protocol ?

**Comment by brrd** [comment] 2020-04-06 08:59
> DeprecationWarning: Passing functions, DOM objects and other non-cloneable JavaScript objects to IPC methods is deprecated and will throw an exception beginning with Electron 9

Electron-tabs doesn't use IPC. It is not communicating with the main process at all. Obviously this warning is related to another part of your application.

Please try running your code in Electron 9 in order to get a real exception, then post the exception message in this thread if it appears to be related to electron-tabs.

>  Is there a reason that only 'file' protocol maybe used as opposed to a custom scheme protocol ?

I don't understand your question. 
If you're talking about webview src, then please refer to Electron's webview documentation: https://www.electronjs.org/docs/api/webview-tag#webviewloadurlurl-options

> the url must contain the protocol prefix, e.g. the http:// or file://.

**Comment by stuartambient** [comment] 2020-04-06 12:40
>

>  Electron-tabs doesn't use IPC. It is not communicating with the main process at all. Obviously this warning is related to another part of your application.

> 
As I mentioned though main is still 'aware' of the webview call.  Using the event listener 'will-attach-webview' in main, it returns all the webPreferences and params configured for the tab.  Those objects can also be modified.  

> Please try running your code in Electron 9 in order to get a real exception, then post the exception message in this thread if it appears to be related to electron-tabs.
> 
Yes, please allow me a few days before closing this issue.  I'll do some testing.  So far the warning only appears when the tab / webview is created.

**Comment by brrd** [comment] 2020-04-06 13:18
> electron-tabs version: 0.12.1

This version is outdated.

> As I mentioned though main is still 'aware' of the webview call. Using the event listener 'will-attach-webview' in main, it returns all the webPreferences and params configured for the tab. Those objects can also be modified.

Er, yes. Nothing unexpected here, this comes from Electron API: `will-attach-webview` event is triggered when a webview is created, and electron-tab uses webviews. This is totally supported and not related to the warning you get, which concerns IPC as explained here: https://www.electronjs.org/docs/breaking-changes#behavior-changed-sending-non-js-objects-over-ipc-now-throws-an-exception

Anyway, I couldn't reproduce this issue and I'm quite sure it is not related to electron-tabs. Do you get the warning when running `npm run demo` in electron-tabs latest version?

**Comment by stuartambient** [comment] 2020-04-06 14:00
> 
> 
> > electron-tabs version: 0.12.1
> 
> This version is outdated.
> 
I'll update, thank you for pointing it out.

> Anyway, I couldn't reproduce this issue and I'm quite sure it is not related to electron-tabs. Do you get the warning when running `npm run demo` in electron-tabs latest version?

Demo runs fine.  I'll dig through my code more to try and find what is causing this issue.  Just a note, not shown here - to load my local html file (not for the webview) along with its assets I have a registerFileProtocol in main. However for the tab and webview using the custom scheme does not work.  Like I can't say in the tab configuration `src: app://myfile.html`, even though the scheme 'app' serves files.    I had to use `src: file://myfile.html`.   Below is my code for the tab. 

 

```
 let tab = tabGroup.addTab({
          title: e.target.textContent,
         // I set src and preload now in main, when will-attach-webview is called
          //src: html, 
          webviewAttributes: {
            nodeIntegration: true,
            NodeIntegrationInSubFrames: true,
            webSecurity: false,
            disableWebSecurity: true,
           // setting preload in main as above with src
            //preload: preload,
          },
        });
        let webview = tab.webview;
       webview.addEventListener("dom-ready", (e) => {
         tab.activate();
         webview.openDevTools();
         sendView(webview, tab);
 
 async function sendView(webview, tab) {
   await webview.send("open:tab", [webview, tab]);
 `
```

**Comment by brrd** [comment] 2020-04-06 14:17
> Demo runs fine.

So your issue is definitely not related to electron-tabs. I'm closing this thread.

>  Just a note, not shown here - to load my local html file (not for the webview) along with its assets I have a registerFileProtocol in main. However for the tab and webview using the custom scheme does not work. Like I can't say in the tab configuration src: app://myfile.html, even though the scheme 'app' serves files. I had to use src: file://myfile.html.

electron-tab is using webview src attribute under the hood without any modification. Please ask your question in Electron forums since we do not deal with registerFileProtocol here.

> // I set src and preload now in main, when will-attach-webview is called

This is not the recommended way to use electron-tabs. I can't guarantee it will work as expected if you are using it this way.

> webview.send("open:tab", [webview, tab]);

Not 100% sure, but your IPC warning is probably caused by this instruction, since `webview.send()` uses IPC and `webview` and `tab` contain DOM elements.

**Closed by brrd** 2020-04-06 14:17 UTC
Labels: need info

**Comment by stuartambient** [comment] 2020-04-06 14:20
Thanks for the help on this one.  Apologies as my webview.send() hadn't crossed my mind earlier.
