### ISSUE TITLE
Demo broken - Webview covers tabs

### ISSUE THREAD

**Issue by electronart** [brrd/electron-tabs#84] opened 2019-10-30 14:09 UTC
When clicking a tab in the webview in the demo application, the webview is positioned absolutely in such a way that it hides the tabs.

**Comment by brrd** [comment] 2019-10-30 14:14
Which version are you using? Downloaded from npm or git? What is your OS? Can you share a screenshot?

**Comment by runyanp** [comment] 2019-11-05 19:50
I'm seeing the same thing on 0.11.0. Cloned from Git. Windows 8.1

![AF202CC7-3368-4247-B347-9A10BDB4C54C](https://user-images.githubusercontent.com/545667/68240740-0b0b8f00-ffd3-11e9-85ed-e6efe64e732c.GIF)

**Comment by brrd** [comment] 2019-11-06 10:07
@runyanp Thank you for this useful information.
Obviously this is a regression introduced by #59/#60. 
I will look for a fix when I get enough time to work on this issue. Until then you can use version 0.10.0 which works well on windows.

**Comment by ChandlerCPrice** [comment] 2019-12-08 14:06
@brrd  I found a solution. Please see the code below:
// Inject styles
(function () {
    const styles = `
            webview {
            width: 1px;
            heigth: 0px;
        }
            webview.visible {
            width: 100%;
            height: 100%;
            position: relative;
            visibility: visible;
        }
       
    `;

**Comment by brrd** [comment] 2019-12-08 14:20
@ChandlerCPrice this is exactly the solution we used before, but we changed this in order to solve #59.
See 1e4e5b0f0750d4e253f4eebcaf23b6485f6e63c6

Obviously everyone is trying to solve his own little problem without caring about other platforms/situations. We need to find a robust solution which works under every platform, and this requires a lot of testing. Unfortunately I lack time right now to work on this.

**Comment by ChandlerCPrice** [comment] 2019-12-10 02:47
@brrd  I don't have a solution for the remaining tabs as the function only seems to work with the first tab, but here's what I did that fixed the first page from inheriting the content from the other tabs. The issue is that each tab after the first tab will inherit some content from the previous tab. The original issue no longer occurs(one tab removes the remaining tabs), the user will see the pages, but every tab except for the first tab will show content from the previous tab. I know you don't have time to fix it, I am just letting you know what I have altered to fix the original issue.

// Inject styles
(function () {
 
    let styleTag = document.createElement("style");
    document.getElementsByTagName("head")[0].appendChild(styleTag);
    const styles = `
        
    webview.visible {
        width: 100%;
        height: 100%;
        position: absolute;
        visibility: visible;
    }
       
    `;
    styleTag.innerHTML = styles;
  
  
    
 

    
}

)();

**Comment by ChandlerCPrice** [comment] 2019-12-10 04:49
@brrd @runyanp @electronart 
I don't know if this will work for you all, but I did this and it fixed the view as well as the original issue of this thread:


// Inject styles
(function () {
    const styles = `
    webview {
        position: absolute;
        visibility: hidden; 
    }  
    webview.visible {
        width: 100%;
        height: 100%;
        visibility: visible
    }
       
    `;
    
 
    let styleTag = document.createElement("style");
    styleTag.innerHTML = styles;
    document.getElementsByTagName("head")[0].appendChild(styleTag);
    
 
  
  
    
 

    
}

)();

**Comment by kakyoism** [comment] 2020-01-22 10:15
> @brrd @runyanp @electronart
> I don't know if this will work for you all, but I did this and it fixed the view as well as the original issue of this thread:
> 
> // Inject styles
> (function () {
> const styles = `
> webview {
> position: absolute;
> visibility: hidden;
> }
> webview.visible {
> width: 100%;
> height: 100%;
> visibility: visible
> }
> 
> ```
> `;
> 
> 
> let styleTag = document.createElement("style");
> styleTag.innerHTML = styles;
> document.getElementsByTagName("head")[0].appendChild(styleTag);
> ```
> 
> }
> 
> )();

Thanks. This is a life-saver! Why haven't this been merged in?

**Comment by brrd** [comment] 2020-01-22 10:31
> Why haven't this been merged in?

This code was first used in electron-tabs, but it raised other issues on OSX (see PRs). Until now, each new patch brought by an OSX contributor introduced new bugs, making other OSX users complaining and asking to get back to the previous code. Since I'm a Windows/Linux user, it's really difficult for me to have a clear idea about what happens exactly and how to solve this.

What I need to do to finally close this debate is to set up a virtual machine for OSX in order to try the different alternatives, and test it on every platform to be sure this doesn't introduce any regression. It takes time, which is why I haven't been able to deal with it until now.

**Comment by kakyoism** [comment] 2020-01-22 12:58
> > Why haven't this been merged in?
> 
> This code was first used in electron-tabs, but it raised other issues on OSX (see PRs). Until now, each new patch brought by an OSX contributor introduced new bugs, making other OSX users complaining and asking to get back to the previous code. Since I'm a Windows/Linux user, it's really difficult for me to have a clear idea about what happens exactly and how to solve this.
> 
> What I need to do to finally close this debate is to set up a virtual machine for OSX in order to try the different alternatives, and test it on every platform to be sure this doesn't introduce any regression. It takes time, which is why I haven't been able to deal with it until now.

Oh, sorry. I didn't realize that you are THE author. Please take no offense from my former comment, OK? This is a well-documented and functional package. Without it I might have dropped Electron completely for any ancient widget tech, but I do believe that the web way is a much better approach in the long run. Thanks for the hard work!

I'm a macOS user and in the next month I'll be heavily using electron-tab.

**Comment by brrd** [comment] 2020-01-22 14:09
> Oh, sorry. I didn't realize that you are THE author. Please take no offense from my former comment, OK? 

No offense, of course 😉

**Comment by brrd** [comment] 2020-02-04 10:53
After a bit of investigation it appears that our initial issue with `display: none` and `visibility: hidden;` was fixed in electron 3: https://github.com/electron/electron/issues/5110

So we can use `visibility: hidden;` again to fix this.

**Closed** 2020-02-04 12:39 UTC
Labels: bug
