### ISSUE TITLE
Tab Navigation broken?

### ISSUE THREAD

**Issue by AhmadHrb** [brrd/electron-tabs#107] opened 2020-06-08 19:56 UTC
**Describe the bug**
When I click on any tab. it gets active and I see it's webview. but when I click on another tab (which was clicked before), nothing changes.

So, let's say I open app, I make a tab and load Google.
I open another tab and load Amazon.
Both of them will get background of white color indicating both are active.
when I click on the Google tab, nothing happens. I stay on Amazon.
when I close amazon, I'am able to load Google tab.

**To Reproduce**
1- Create a tab.
2- Create another tab.
3- connot load 1st tab anymore.

**Expected behavior**
I should be able to load any tab when I click on it.

**Please complete the following information**
 - OS: Windows 10
 - electron-tabs version 0.15.0
 - Electron version 9.0.0

**Code**
If your issue involves code, please consider creating a sample in a dedicated repository.

**Screenshots**
![image](https://user-images.githubusercontent.com/34627272/84074036-8fdfe080-a9da-11ea-8c60-44b855ac9b15.png)
**Additional information**
Thanks.

**Comment by brrd** [comment] 2020-06-09 06:45
Can you please try the demo and tell us if this issue also happen in it?

```
git clone https://github.com/brrd/electron-tabs.git
cd electron-tabs
npm install
npm run demo
```

**Comment by AhmadHrb** [comment] 2020-06-09 08:12
No. I noticed it doesn't happen.
No idea why it only happens on my app.

My Index.html:
```
 <div class="etabs-tabgroup bg-light">
            <div class="etabs-tabs"></div>
            <div class="etabs-buttons"></div>
          </div>
          <div class="etabs-views"></div>
        <script>
            const TabGroup = require("electron-tabs");
    let tabGroup = new TabGroup();
    let tab = tabGroup.addTab({
        title: "New Tab"
    });
    
        </script> 
```

I have a <nav> above the tabs. but I don't see that's related.

**Comment by brrd** [comment] 2020-06-09 08:32
Any log in the devtools console?

**Comment by AhmadHrb** [comment] 2020-06-09 08:53
Nope, nothing at all.

**Comment by brrd** [comment] 2020-06-09 09:21
I thing something is wrong in your code. We can not help you unless you provide more code.

**Comment by AhmadHrb** [comment] 2020-06-09 09:51
A copy of my current code is on https://github.com/PocketInc/Pocket-Browser/tree/v1.3

**Comment by brrd** [comment] 2020-06-09 10:03
I think there is something wrong in https://github.com/PocketInc/Pocket-Browser/blob/09547698ab9f483052da602409a015fc9be1fc16/tabs.js

```js
function addTab() {
  const TabGroup = require("electron-tabs");
  let tabGroup = new TabGroup();
  let tab = tabGroup.addTab({
    src: homePage,
    title: "New Tab",
  });

  log.info("Opening new tab.");
}
```

Each time you use `addTab()` this creates a new tabGroup with a single tab.

Try this instead:

```js
const TabGroup = require("electron-tabs");
const tabGroup = new TabGroup();

function addTab() {
  let tab = tabGroup.addTab({
    src: homePage,
    title: "New Tab",
  });

  log.info("Opening new tab.");
}
```

And make sure this code is run once document is ready.

I'm closing this issue since it is not caused by electron-tabs.

**Closed by brrd** 2020-06-09 10:03 UTC
Labels: need info

**Comment by AhmadHrb** [comment] 2020-06-09 10:13
Thank you. I can't imagine how I fell in such thing XD
Thanks again, and sorry for the trouble.
